set(sources
    src/ChildState.cpp
    src/Exec.cpp
    src/ExitStatus.cpp
    src/Popen.cpp
    src/PopenConfig.cpp
    src/PopenError.cpp
    src/posix.cpp
    src/PrepExec.cpp
    src/Redirection.cpp
    src/Pipeline.cpp
)

set(exe_sources
		${sources}
)

set(detail_headers
    include/subprocess/detail/ChildState.hpp
    include/subprocess/detail/platform.hpp
    include/subprocess/detail/posix.hpp
    include/subprocess/detail/PrepExec.hpp
    include/subprocess/detail/RaggedCstrArray.hpp
    include/subprocess/detail/type_name.hpp
    include/subprocess/detail/variant_helpers.hpp
)

set(headers
    include/subprocess/CaptureData.hpp
    include/subprocess/Exec.hpp
    include/subprocess/ExitStatus.hpp
    include/subprocess/Popen.hpp
    include/subprocess/PopenConfig.hpp
    include/subprocess/PopenError.hpp
    include/subprocess/Redirection.hpp
    include/subprocess/Result.hpp
    include/subprocess/Pipeline.hpp
    include/subprocess/operators.hpp
    ${detail_headers}
)
