name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
          key: ${{ runner.os }}-dependencies

      - name: install Catch2
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          cd ..
          git clone https://github.com/catchorg/Catch2.git --branch v2.x
          cd Catch2
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
          cmake --build build --config Release
          cmake --build build --target install --config Release

      - name: configure
        run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -DSubprocess_ENABLE_CODE_COVERAGE=1

      - name: build
        run: cmake --build build --config $BUILD_TYPE -j4

      - name: run tests
        run: |
          cd build
          ctest -C $BUILD_TYPE -VV

      - name: Code coverage using Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: install project
        run: cmake --build build --target install --config Release
